name: license-guard
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure license files exist
        run: |
          test -f LICENSE
          test -f NOTICE
